[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_BASE_URL = "/"
  NODE_VERSION = "18"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 